device_identifiers = \
[(11, 'DC Brick', 'dc_brick'),
 (13, 'Master Brick', 'master_brick'),
 (14, 'Servo Brick', 'servo_brick'),
 (15, 'Stepper Brick', 'stepper_brick'),
 (16, 'IMU Brick', 'imu_brick'),
 (17, 'RED Brick', 'red_brick'),
 (18, 'IMU Brick 2.0', 'imu_v2_brick'),
 (21, 'Ambient Light Bricklet', 'ambient_light_bricklet'),
 (23, 'Current12 Bricklet', 'current12_bricklet'),
 (24, 'Current25 Bricklet', 'current25_bricklet'),
 (25, 'Distance IR Bricklet', 'distance_ir_bricklet'),
 (26, 'Dual Relay Bricklet', 'dual_relay_bricklet'),
 (27, 'Humidity Bricklet', 'humidity_bricklet'),
 (28, 'IO-16 Bricklet', 'io16_bricklet'),
 (29, 'IO-4 Bricklet', 'io4_bricklet'),
 (210, 'Joystick Bricklet', 'joystick_bricklet'),
 (211, 'LCD 16x2 Bricklet', 'lcd_16x2_bricklet'),
 (212, 'LCD 20x4 Bricklet', 'lcd_20x4_bricklet'),
 (213, 'Linear Poti Bricklet', 'linear_poti_bricklet'),
 (214, 'Piezo Buzzer Bricklet', 'piezo_buzzer_bricklet'),
 (215, 'Rotary Poti Bricklet', 'rotary_poti_bricklet'),
 (216, 'Temperature Bricklet', 'temperature_bricklet'),
 (217, 'Temperature IR Bricklet', 'temperature_ir_bricklet'),
 (218, 'Voltage Bricklet', 'voltage_bricklet'),
 (219, 'Analog In Bricklet', 'analog_in_bricklet'),
 (220, 'Analog Out Bricklet', 'analog_out_bricklet'),
 (221, 'Barometer Bricklet', 'barometer_bricklet'),
 (222, 'GPS Bricklet', 'gps_bricklet'),
 (223, 'Industrial Digital In 4 Bricklet', 'industrial_digital_in_4_bricklet'),
 (224,
  'Industrial Digital Out 4 Bricklet',
  'industrial_digital_out_4_bricklet'),
 (225, 'Industrial Quad Relay Bricklet', 'industrial_quad_relay_bricklet'),
 (226, 'PTC Bricklet', 'ptc_bricklet'),
 (227, 'Voltage/Current Bricklet', 'voltage_current_bricklet'),
 (228, 'Industrial Dual 0-20mA Bricklet', 'industrial_dual_0_20ma_bricklet'),
 (229, 'Distance US Bricklet', 'distance_us_bricklet'),
 (230, 'Dual Button Bricklet', 'dual_button_bricklet'),
 (231, 'LED Strip Bricklet', 'led_strip_bricklet'),
 (232, 'Moisture Bricklet', 'moisture_bricklet'),
 (233, 'Motion Detector Bricklet', 'motion_detector_bricklet'),
 (234, 'Multi Touch Bricklet', 'multi_touch_bricklet'),
 (235, 'Remote Switch Bricklet', 'remote_switch_bricklet'),
 (236, 'Rotary Encoder Bricklet', 'rotary_encoder_bricklet'),
 (237, 'Segment Display 4x7 Bricklet', 'segment_display_4x7_bricklet'),
 (238, 'Sound Intensity Bricklet', 'sound_intensity_bricklet'),
 (239, 'Tilt Bricklet', 'tilt_bricklet'),
 (240, 'Hall Effect Bricklet', 'hall_effect_bricklet'),
 (241, 'Line Bricklet', 'line_bricklet'),
 (242, 'Piezo Speaker Bricklet', 'piezo_speaker_bricklet'),
 (243, 'Color Bricklet', 'color_bricklet'),
 (244, 'Solid State Relay Bricklet', 'solid_state_relay_bricklet'),
 (245, 'Heart Rate Bricklet', 'heart_rate_bricklet'),
 (246, 'NFC/RFID Bricklet', 'nfc_rfid_bricklet'),
 (249,
  'Industrial Dual Analog In Bricklet',
  'industrial_dual_analog_in_bricklet'),
 (250, 'Accelerometer Bricklet', 'accelerometer_bricklet'),
 (251, 'Analog In Bricklet 2.0', 'analog_in_v2_bricklet'),
 (252, 'Gas Detector Bricklet', 'gas_detector_bricklet'),
 (253, 'Load Cell Bricklet', 'load_cell_bricklet'),
 (254, 'RS232 Bricklet', 'rs232_bricklet'),
 (255, 'Laser Range Finder Bricklet', 'laser_range_finder_bricklet'),
 (256, 'Analog Out Bricklet 2.0', 'analog_out_v2_bricklet'),
 (257, 'AC Current Bricklet', 'ac_current_bricklet'),
 (258, 'Industrial Analog Out Bricklet', 'industrial_analog_out_bricklet'),
 (259, 'Ambient Light Bricklet 2.0', 'ambient_light_v2_bricklet'),
 (260, 'Dust Detector Bricklet', 'dust_detector_bricklet'),
 (262, 'CO2 Bricklet', 'co2_bricklet'),
 (263, 'OLED 128x64 Bricklet', 'oled_128x64_bricklet'),
 (264, 'OLED 64x48 Bricklet', 'oled_64x48_bricklet'),
 (265, 'UV Light Bricklet', 'uv_light_bricklet'),
 (266, 'Thermocouple Bricklet', 'thermocouple_bricklet'),
]
